name: velsik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  flash: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/apv.png
    - assets/handlingsplan.png
    - assets/moeder-og-referater.png
    - assets/medarbejdere.png
    - assets/opret-apv.png
    - assets/nuvaerende-apv.png
    - assets/tidligere-apv.png
    - assets/byggeoganlaeg.png
    - assets/butikogengros.png
    - assets/log-ud.png
    - assets/nÃ¦ste.png
    - assets/send.png
    - assets/Fald til lavere niveau.png
    - assets/Fald og snublen.png

